- name: Ensure gpg package installed
  apt:
    name: gpg
    state: present

- name: Ensure prometheus-node-exporter package installed
  apt:
    name: prometheus-node-exporter
    state: present

- name: Set up apt-key for controlplane repo
  apt_key:
    url: https://europe-north1-apt.pkg.dev/doc/repo-signing-key.gpg
    state: present

- name: Set up controlplane repo
  apt_repository:
    repo: 'deb [arch=amd64] https://europe-north1-apt.pkg.dev/projects/naisdevice controlplane main'
    state: present

- name: Ensure apiserver package installed
  apt:
    name: apiserver
    state: present

# TODO: remove
- name: Create binary directory
  file:
    path: /opt/nais-device/bin
    state: directory
    mode: '0755'

- name: Get secrets
  shell: gcloud --project nais-device secrets versions access latest --secret {{ item.secret }}
  args:
    executable: /bin/bash
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
  register: secrets
  loop:
    - env: APISERVER_DBCONNDSN
      secret: apiserver-db-dsn
    - env: APISERVER_AZURECLIENTSECRET
      secret: azure-client-secret
    - env: APISERVER_KOLIDEAPITOKEN
      secret: kolide-api-token
    - env: APISERVER_KOLIDEEVENTHANDLERTOKEN
      secret: kolide-event-handler-grpc-auth-token
    - env: APISERVER_BOOTSTRAPAPICREDENTIALS
      secret: nais-device_api-server_bootstrap-api-password
    - env: APISERVER_JITAPASSWORD
      secret: naisdevice-jita-password

- name: API server configuration
  template:
    src: configuration.j2
    dest: /etc/default/apiserver
    owner: root
    group: root
    mode: '0600'
  #notify:
  #  - restart_apiserver

- name: Ensure apiserver is enabled
  systemd:
    name: apiserver
    enabled: yes
    daemon_reload: yes

- name: Ensure apiserver is started
  systemd:
    name: apiserver
    state: started

- name: Add logrotate config
  template:
    owner: root
    mode: 640
    src: logrotate-apiserver.j2
    dest: /etc/logrotate.d/naisdevice-apiserver
