- name: Ensure wireguard package installed
  apt:
    name: wireguard
    state: present

- name: Create binary directory
  file:
    path: /opt/nais-device/bin
    state: directory
    mode: '0755'

- name: Download apiserver
  get_url:
    dest: /opt/nais-device/bin/apiserver
    force: yes
    url: https://github.com/nais/device/releases/download/2021-07-13-115734/apiserver
    backup: yes
    mode: 0755
  notify:
    - restart_apiserver

- name: Install apiserver systemd unit file
  template:
    src: apiserver.service.j2
    dest: /etc/systemd/system/apiserver.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_apiserver

- name: Ensure apiserver is enabled
  systemd:
    name: apiserver
    enabled: yes
    daemon_reload: yes

- name: Ensure apiserver is started
  systemd:
    name: apiserver
    state: started

- name: Uninstall naisdevice-health-checker systemd service file
  file:
    path: /etc/systemd/system/naisdevice-health-checker.service
    state: absent
  notify:
    - systemd_reload

- name: Install naisdevice-health-checker systemd timer file
  file:
    path: /etc/systemd/system/naisdevice-health-checker.timer
    state: absent
  notify:
    - systemd_reload

- name: ensure naisdevice-health-checker.timer is enabled
  systemd:
    name: naisdevice-health-checker.timer
    enabled: no
    state: stopped
    daemon_reload: yes

- name: ensure naisdevice-health-checker.service is disabled
  systemd:
    name: naisdevice-health-checker.service
    enabled: no
    state: stopped
    daemon_reload: yes

- name: Add logrotate config
  template:
    owner: root
    mode: 640
    src: logrotate-apiserver.j2
    dest: /etc/logrotate.d/naisdevice-apiserver
