- name: Ensure wireguard package installed
  apt:
    name: wireguard
    state: present

- name: Create binary directory
  file:
    path: /opt/nais-device/bin
    state: directory
    mode: '0755'

- name: Download apiserver
  get_url:
    dest: /opt/nais-device/bin/apiserver
    force: yes
    url: https://github.com/nais/device/releases/download/2021-12-03-104505/apiserver
    backup: yes
    mode: 0755
  notify:
    - restart_apiserver

- name: Install apiserver systemd unit file
  template:
    src: apiserver.service.j2
    dest: /etc/systemd/system/apiserver.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart_apiserver

- name: API server configuration
  template:
    src: configuration.j2
    dest: /etc/default/apiserver
    owner: root
    group: root
    mode: '0600'
  notify:
    - restart_apiserver

- name: Get enrollment token
  shell: gcloud --project nais-device secrets versions access latest --secret {{ item }}
  args:
    executable: /bin/bash
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
  register: secrets
  loop:
    - apiserver-db-dsn
    - azure-client-secret
    - kolide-api-token
    - kolide-event-handler-grpc-auth-token
    - nais-device_api-server_bootstrap-api-password
    - naisdevice-jita-password

- name: Ensure apiserver is enabled
  systemd:
    name: apiserver
    enabled: yes
    daemon_reload: yes

- name: Ensure apiserver is started
  systemd:
    name: apiserver
    state: started

- name: Uninstall naisdevice-health-checker systemd service file
  file:
    path: /etc/systemd/system/naisdevice-health-checker.service
    state: absent
  notify:
    - systemd_reload

- name: Add logrotate config
  template:
    owner: root
    mode: 640
    src: logrotate-apiserver.j2
    dest: /etc/logrotate.d/naisdevice-apiserver
