- name: Ensure wireguard package installed
  apt:
    name: wireguard
    state: present

- name: Create binary directory
  file:
    path: /opt/nais-device/bin
    state: directory
    mode: '0755'

- name: Download apiserver
  get_url:
    dest: /opt/nais-device/bin/apiserver
    force: yes
    url: https://github.com/nais/device/releases/download/2020-11-09-2cc0199/apiserver
    backup: yes
    mode: 0755
  notify:
    - restart_apiserver

- name: Install apiserver systemd unit file
  template:
    src: apiserver.service.j2
    dest: /etc/systemd/system/apiserver.service
  notify:
    - restart_apiserver

- name: Ensure apiserver is enabled
  systemd:
    name: apiserver
    enabled: yes
    daemon_reload: yes

- name: Ensure apiserver is started
  systemd:
    name: apiserver
    state: started

- name: Download naisdevice-health-checker.phar
  get_url:
    dest: /opt/nais-device/bin/naisdevice-health-checker.phar
    force: yes
    url: https://github.com/nais/naisdevice-health-checker/releases/download/2020-11-09-33e2140/naisdevice-health-checker.phar
    backup: yes
    mode: 0755

- name: Install naisdevice-health-checker systemd unit file
  template:
    src: naisdevice-health-checker.service.j2
    dest: /etc/systemd/system/naisdevice-health-checker.service
  notify:
    - restart_naisdevice-health-checker

- name: Install naisdevice-health-checker systemd timer file
  file:
    src: naisdevice-health-checker.timer
    path: /etc/systemd/system/naisdevice-health-checker.timer
  notify:
    - restart_naisdevice-health-checker

- name: Ensure naisdevice-health-checker is enabled
  systemd:
    name: naisdevice-health-checker
    enabled: yes
    daemon_reload: yes

- name: Ensure naisdevice-health-checker is started
  systemd:
    name: naisdevice-health-checker
    state: started
