- name: Create admin group
  group:
    name: admin
    gid: 1069
    state: present

- name: nopasswd for members of 'sudo' group
  copy:
    mode: '0600'
    owner: root
    group: root
    dest: /etc/sudoers.d/sudo-group-nopasswd
    content: '%sudo ALL=(ALL:ALL) NOPASSWD:ALL'

- name: Create admin users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.name }}"
    shell: "/bin/bash"
    group: "admin"
    groups: "sudo"
    state: present
  when: admin_users is defined
  loop: "{{ admin_users }}"

- name: Add admin_users  ssh keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.authorized_key }}"
    state: present
  when: admin_users is defined and item.authorized_key is defined
  loop: "{{ admin_users }}"

- name: Add logrotate config
  template:
    owner: root
    group: root
    mode: 640
    src: logrotate-gateway-agent.j2
    dest: /etc/logrotate.d/naisdevice-gateway-agent
