- name: Add Google Cloud Logging apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Google Cloud Logging repository
  apt_repository:
    repo: deb https://packages.cloud.google.com/apt google-cloud-logging-focal-all main
    update_cache: yes

- name: Install Google Cloud Logging agent
  apt:
    name: google-fluentd
    state: present
    policy_rc_d: 101 # disable automatic start

- name: Ensure /etc/google/auth/ directory
  file:
    path: /etc/google/auth/
    state: directory
    mode: 0755

- name: Download google cloud log write SA credentials
  shell: gcloud --project nais-device secrets versions access latest --secret logwriter-credentials > /etc/google/auth/application_default_credentials.json
  args:
    creates: /etc/google/auth/application_default_credentials.json
    executable: /bin/bash
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

- name: Logging configuration
  template:
    src: naisdevice.conf.j2
    dest: /etc/google-fluentd/google-fluentd.conf
  notify:
    - restart_google-fluentd

- name: Create systemd unit override directory
  when: onprem is defined and onprem == true
  file:
    path: /etc/systemd/system/google-fluentd.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Add systemd unit override
  when: onprem is defined and onprem == true
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/google-fluentd.service.d/override.conf
  notify:
    - restart_google-fluentd
