- name: Add Google Cloud Logging apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Google Cloud Logging repository
  apt_repository:
    repo: deb https://packages.cloud.google.com/apt google-cloud-logging-focal-all main
    update_cache: yes

- name: Install Google Cloud Logging agent
  apt:
    name: google-fluentd
    state: present

- name: Ensure /var/log/naisdevice/ permissions
  file:
    path: /var/log/naisdevice
    state: directory
    owner: fluentd
    group: syslog
    mode: 0755

- name: Ensure /etc/google/auth/ directory
  file:
    path: /etc/google/auth/
    state: directory
    mode: 0755

- name: Download google cloud log write SA credentials
  shell: gcloud --project nais-device secrets versions access latest --secret logwriter-credentials > /etc/google/auth/application_default_credentials.json
  args:
    creates: /etc/google/auth/application_default_credentials.json
    executable: /bin/bash
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

- name: Create google-fluentd config directory
  file:
    path: /etc/google-fluentd/config.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Logging configuration
  template:
    src: naisdevice.conf.j2
    dest: /etc/google-fluentd/google-fluentd.conf
  notify:
    - restart_google-fluentd
