- name: Set up apt-key for controlplane repo
  apt_key:
    url: https://europe-north1-apt.pkg.dev/doc/repo-signing-key.gpg
    state: present

- name: Set up controlplane repo
  apt_repository:
    repo: 'deb [arch=amd64] https://europe-north1-apt.pkg.dev/projects/naisdevice controlplane main'
    state: present

- name: Ensure wireguard package installed
  apt:
    name: wireguard
    state: present

- name: Ensure prometheus package installed
  apt:
    name: prometheus
    state: present

- name: Ensure prometheus-agent package installed
  apt:
    name: prometheus-agent
    state: present

- name: Copy prometheus config
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/
  notify:
    - restart_prometheus

- name: Ensure prometheus-agent is enabled
  systemd:
    name: prometheus-agent
    enabled: yes
    daemon_reload: yes

- name: Ensure prometheus-agent is started
  systemd:
    name: prometheus-agent
    state: started

- name: Add logrotate config
  template:
    owner: root
    group: root
    mode: 640
    src: logrotate-prometheus-agent.j2
    dest: /etc/logrotate.d/naisdevice-prometheus-agent
