- name: Ensure wireguard package installed
  apt:
    name: wireguard
    state: present

- name: Ensure prometheus package installed
  apt:
    name: prometheus
    state: present

- name: Create binary directory
  file:
    path: /opt/naisdevice/bin
    state: directory
    mode: '0755'

- name: Download prometheus-agent
  get_url:
    dest: /opt/naisdevice/bin/prometheus-agent
    force: yes
    url: https://github.com/nais/device/releases/download/2021-10-04-111116/prometheus-agent
    backup: yes
    mode: 0755
  notify:
    - restart_prometheus-agent

- name: Copy prometheus config
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/
  notify:
    - restart_prometheus

- name: Install prometheus-agent systemd unit file
  template:
    src: prometheus-agent.service.j2
    dest: /etc/systemd/system/prometheus-agent.service
  notify:
    - restart_prometheus-agent

- name: Ensure prometheus-agent is enabled
  systemd:
    name: prometheus-agent
    enabled: yes
    daemon_reload: yes

- name: Ensure prometheus-agent is started
  systemd:
    name: prometheus-agent
    state: started

- name: Add logrotate config
  template:
    owner: root
    group: root
    mode: 640
    src: logrotate-prometheus-agent.j2
    dest: /etc/logrotate.d/naisdevice-prometheus-agent
