---
- hosts: bootstrap_api
  roles:
    - logging
    - bootstrap-api

- hosts: prometheus
  roles:
    - logging
    - prometheus

- hosts: apiservers
  roles:
    - logging
    - apiserver

- hosts: gateways
  roles:
    - logging
    - gateway
  vars:
    K8S_CLUSTER_API_IP_ADDRESS: 172.10.0.2
    onprem: false

- hosts: onprem_gateways
  environment: "{{ proxy_env }}"
  vars:
    onprem: true
    admin_users:
      - name: m152973
        authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO7fYA2cjne20QGuDjsVAorHikWPB5iPVzfbh/ej6pWZ vegar@sechmann.no-20190405\nssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB49qLBkoHhlnpf7HxhcjIozk2ffeOQdAwaElMbusQ9J vegar@laptux-vegar-nav"
      - name: h129009
        authorized_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHsIXwF/eT74JubXMiAmk1Qwxs4VgZESy/JT/0gKTRG1 johnny@horvi.no-2019-05-15"
      - name: r137915
        authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDutPpwpMPlrcNYbZi/Yp3tuidx0fbH5lINAt03AUbGrjcplIas89bNVFPqEZZkjW7pToviaAVZPbWvNOc4buve/dm8PuvjiIiD/TcWlBWYVG2awYTXxIlETA6S4zklFicv2GjgdVOCV3N2ttyLYF1Q2fGHaZU1KJQg1vEcL4JtOtecmMvEG8mwXXNEHAP+gGJPwghFV7zfZRkrnT3Jcw59NjAidnRCv9d7XPNH3+/zgwl+eem20jKxBjOd8r1qFaJ3raUxvcm05BMC65O5jeUXSakz1cnD4NqO9pTwGbDLos4FCh36FmqbYZqYGLoQScw2ohOtudlJxm9c+higHuT1 stenrokke@Stens-MacBook-Pro.local"
  roles:
    - onprem-gateway
    - logging
    - gateway
