- name: Ensure wireguard package installed
  apt:
    name: gpg
    state: present

- name: Ensure prometheus-node-exporter package installed
  apt:
    name: prometheus-node-exporter
    state: present

- name: Set up apt-key for controlplane repo
  apt_key:
    url: https://europe-north1-apt.pkg.dev/doc/repo-signing-key.gpg
    state: present

- name: Set up controlplane repo
  apt_repository:
    repo: 'deb [arch=amd64] https://europe-north1-apt.pkg.dev/projects/naisdevice controlplane main'
    state: present

- name: Ensure gateway-agent package installed
  apt:
    name: gateway-agent
    state: present

- name: Enable IPv4 forwarding in sysctl
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    reload: yes

- name: Ensure config dir
  file:
    path: /etc/gateway-agent
    state: directory
    mode: '0755'

- name: Check for existing gateway-config
  stat:
    path: /usr/local/etc/nais-device
  register: private_key

- name: Move private key if already generated
  copy:
    remote_src: True
    src: /usr/local/etc/nais-device/
    dest: /etc/gateway-agent/
  when: private_key.stat.exists
  notify:
    - restart_gateway-agent

- name: Remove old config
  file:
    path: /usr/local/etc/nais-device/
    state: absent

- name: Generate wireguard key
  shell: umask 077 && wg genkey > /etc/gateway-agent/private.key
  when: not private_key.stat.exists
  args:
    creates: /etc/gateway-agent/private.key
  notify:
    - restart_gateway-agent

- name: Get apiserver password
  shell: gcloud --project nais-device secrets versions access latest --secret {{ gcp_project }}_{{ name }}_api-server-password
  args:
    executable: /bin/bash
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
  register: apiserver_password

- name: Get enrollment token
  shell: gcloud --project nais-device secrets versions access latest --secret enrollment-token_{{ name }}
  args:
    executable: /bin/bash
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
  register: enrollment_token

- name: Get public ip
  shell: |
    if [[ $(hostname) ~= "a30drvl" ]] then;
      ip -4 -o address show ens160 | awk \'{print $4}\' | cut -d "/" -f 1
    else
      curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip
    fi
  args:
    executable: /bin/bash
  register: public_ip

- name: Gateway config - set vars
  lineinfile:
    path: /etc/default/gateway-agent
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  loop:
    - regexp: "^GATEWAY_AGENT_NAME=.*$"
      line: GATEWAY_AGENT_NAME="{{ name }}"
    - regexp: "^GATEWAY_AGENT_PUBLICIP=.*$"
      line: GATEWAY_AGENT_PUBLICIP="{{ public_ip.stdout }}:51820"
    - regexp: "^GATEWAY_AGENT_ENROLLMENTTOKEN=.*$"
      line: GATEWAY_AGENT_ENROLLMENTTOKEN="{{ enrollment_token.stdout }}"
    - regexp: "^GATEWAY_AGENT_APISERVERPASSWORD=.*$"
      line: GATEWAY_AGENT_APISERVERPASSWORD="{{ apiserver_password.stdout }}"

- name: Remove old gateway agent systemd unit file
  file:
    path: /etc/systemd/system/gateway-agent.service
    state: absent

- name: Ensure gateway-agent is enabled
  systemd:
    name: gateway-agent
    enabled: yes
    daemon_reload: yes

- name: Ensure gateway-agent is started
  systemd:
    name: gateway-agent
    state: started

- include_tasks: install_dmesg_to_json.yml
- include_tasks: set_iptables_rulesv4_outset.yml

- name: Add logrotate config
  template:
    owner: root
    group: root
    mode: 640
    src: logrotate-gateway-agent.j2
    dest: /etc/logrotate.d/naisdevice-gateway-agent
