# This workflow exists only to recover the PPA_GPG_PASSPHRASE, which has been lost
# Once the key has been recovered, this workflow should be deleted
#
# Plan of attack:
# - Encrypt the PPA_GPG_PASSPHRASE using a personal public GPG key
# - Print the encrypted text to the log
# - Copy encrypted text and decrypt locally
# - Add key to Vault for safe keeping
# - Remove this workflow

on: workflow_dispatch

jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
      - name: "Let's dance"
        id: update_ppa
        env:
          PPA_GPG_PASSPHRASE: ${{ secrets.PPA_GPG_PASSPHRASE }}
        run: |
          # Set-up GPG
          mkdir -p ~/.gnupg
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo RELOADAGENT | gpg-connect-agent
          curl https://keybase.io/mortenlj/pgp_keys.asc | gpg --import --batch

          # Encrypt passphrase
          echo ${PPA_GPG_PASSPHRASE} | gpg --batch --no-tty --encrypt --armor --recipient morten.lied.johansen@nav.no -o -
